#!/usr/bin/env bash

pkill polybar

sleep 0.2;

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    if [ $m = "DVI-D-0" ]; then
      MONITOR=$m polybar --reload main_bar &
    else
      MONITOR=$m polybar --reload secondary_bar &
    fi
  done
fi
